Repository karafka/rdkafka-ruby, pull requests merged in 2023-11, with the labels that each got.

#325 Add dates to changelog entries
  CHANGELOG.md
Labels: documentation

#329 Use weak map to remove opaque references
  CHANGELOG.md
  lib/rdkafka/config.rb
  lib/rdkafka/native_kafka.rb
  spec/rdkafka/native_kafka_spec.rb
Labels: bug

#335 Backport purge from karafka-rdkafka
  .ruby-gemset
  .ruby-version
  CHANGELOG.md
  lib/rdkafka/bindings.rb
  lib/rdkafka/producer.rb
  spec/rdkafka/producer_spec.rb
Labels: enhancement, librdkafka

#244 Added Create and Delete ACL Feature To Admin Functions
  lib/rdkafka.rb
  lib/rdkafka/admin.rb
  lib/rdkafka/admin/acl_binding_result.rb
  lib/rdkafka/admin/create_acl_handle.rb
  lib/rdkafka/admin/create_acl_report.rb
  lib/rdkafka/admin/delete_acl_handle.rb
  lib/rdkafka/admin/delete_acl_report.rb
  lib/rdkafka/admin/describe_acl_handle.rb
  lib/rdkafka/admin/describe_acl_report.rb
  lib/rdkafka/bindings.rb
  lib/rdkafka/callbacks.rb
  spec/rdkafka/admin/create_acl_handle_spec.rb
  spec/rdkafka/admin/create_acl_report_spec.rb
  spec/rdkafka/admin/delete_acl_handle_spec.rb
  spec/rdkafka/admin/delete_acl_report_spec.rb
  spec/rdkafka/admin/describe_acl_handle_spec.rb
  spec/rdkafka/admin/describe_acl_report_spec.rb
  spec/rdkafka/admin_spec.rb
Labels: admin

#349 bump librdkafka to 2.3.0
  CHANGELOG.md
  lib/rdkafka/consumer.rb
  lib/rdkafka/version.rb
Labels: librdkafka

#352 update code doc reference and remove milestone
  README.md
Labels: documentation

#353 Add admin#delete_group utility
  lib/rdkafka.rb
  lib/rdkafka/admin.rb
  lib/rdkafka/admin/delete_groups_handle.rb
  lib/rdkafka/admin/delete_groups_report.rb
  lib/rdkafka/bindings.rb
  lib/rdkafka/callbacks.rb
  spec/rdkafka/admin_spec.rb
Labels: admin, librdkafka

#355 backport partitions creation
  CHANGELOG.md
  lib/rdkafka.rb
  lib/rdkafka/admin.rb
  lib/rdkafka/admin/create_partitions_handle.rb
  lib/rdkafka/admin/create_partitions_report.rb
  lib/rdkafka/bindings.rb
  lib/rdkafka/callbacks.rb
  spec/rdkafka/admin_spec.rb
  spec/spec_helper.rb
Labels: admin, librdkafka

#356 Expose alternative poll flow for consumer
  CHANGELOG.md
  lib/rdkafka/config.rb
  lib/rdkafka/consumer.rb
  spec/rdkafka/config_spec.rb
  spec/rdkafka/consumer_spec.rb
  spec/spec_helper.rb
Labels: consumer
