Repository karafka/rdkafka-ruby, pull requests merged in 2024-03, with the labels that each got.

#417 switch to use mutex in AbstractHandle.wait method
  lib/rdkafka/abstract_handle.rb
  lib/rdkafka/callbacks.rb
  spec/spec_helper.rb
Labels: enhancement, producer, performance

#421 fix unlock race condition
  lib/rdkafka/abstract_handle.rb
  lib/rdkafka/admin/create_topic_report.rb
  lib/rdkafka/admin/delete_groups_report.rb
  lib/rdkafka/admin/delete_topic_report.rb
  lib/rdkafka/callbacks.rb
Labels: bug

#410 Oauthbearer token refresh callback
  .gitignore
  lib/rdkafka.rb
  lib/rdkafka/admin.rb
  lib/rdkafka/bindings.rb
  lib/rdkafka/config.rb
  lib/rdkafka/consumer.rb
  lib/rdkafka/helpers/oauth.rb
  lib/rdkafka/producer.rb
  spec/rdkafka/admin_spec.rb
  spec/rdkafka/bindings_spec.rb
  spec/rdkafka/config_spec.rb
  spec/rdkafka/consumer_spec.rb
  spec/rdkafka/producer_spec.rb
  spec/spec_helper.rb
Labels: enhancement, librdkafka

#428 Allow for deferred native kafka start
  CHANGELOG.md
  lib/rdkafka/admin.rb
  lib/rdkafka/config.rb
  lib/rdkafka/consumer.rb
  lib/rdkafka/native_kafka.rb
  lib/rdkafka/producer.rb
  spec/rdkafka/admin_spec.rb
  spec/rdkafka/consumer_spec.rb
  spec/rdkafka/producer_spec.rb
Labels: enhancement, admin, consumer, producer
