Repository karafka/rdkafka-ruby, pull requests merged in 2024-04, with the labels that each got.

#434 name polling Thread as rdkafka.polling
  CHANGELOG.md
  lib/rdkafka/native_kafka.rb
  spec/rdkafka/native_kafka_spec.rb
Labels: enhancement

#437 Fix early return in NativeKafka#start
  lib/rdkafka/native_kafka.rb
Labels: bug

#440 stabilize spec
  spec/rdkafka/admin_spec.rb
Labels: specs

#445 Provide errors describing Admin API
  CHANGELOG.md
  lib/rdkafka/admin.rb
  lib/rdkafka/bindings.rb
  spec/rdkafka/admin_spec.rb
Labels: admin
